name: newsapp_clean
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  # comparing dart objects
  build_runner: ^2.4.6
  cached_network_image: ^3.3.0
  equatable: ^2.0.5
  floor: ^1.4.2
  floor_generator: ^1.4.2
  flutter:
    sdk: flutter
  # state management
  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.20.2
  get_it: ^7.6.4
  intl: ^0.18.1
  retrofit: ^4.0.1
  retrofit_generator: ^7.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli-Bold.ttf
        - asset: assets/fonts/muli/Muli-Light.ttf
        - asset: assets/fonts/muli/Muli.ttf